---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- import_tasks: preflight.yml
  
- import_tasks: tarball_install.yml
  when: mongodb_install_method == "tarball"

- import_tasks: package_install.yml
  when: mongodb_install_method == "package"

- import_tasks: configure.yml

- import_tasks: users.yml
