---

- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: create mongodb system group
  group:
    name: mongod
    system: true
    state: present

- name: create mongod system user
  user:
    name: mongod
    system: true
    shell: "/sbin/nologin"
    group: mongod
    createhome: false
    home: "{{ mongodb_db_path }}"

- name: create mongodb data directory
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    owner: mongod
    group: mongod
    mode: 0755

- name: create mongod log directory
  file:
    path: "{{ mongodb_log_dir }}"
    state: directory
    owner: mongod
    group: mongod
    mode: 0755

- name: Install mongodb dependencies
  package:
    name: "{{ mongodb_dependencies }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2
